

"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import {  useRouter } from "next/navigation";
import { setNavigationRef } from "../componets/common/Navigation";
import ClientWrapper from "@/componets/ClientWrapper";
import { LayoutProvider } from "@/context/LayoutContext";

// Load Google fonts with CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const metadata = {
    title: "P-2-P | Admin Panel",
    description: "Admin Panel",
  };
  const router = useRouter();

  useEffect(() => {
    setNavigationRef(router);
  }, [router]);


 

  return (
    <html lang="en">
      <head>
        {/* Adding metadata in <head> */}
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientWrapper>

          <LayoutProvider>
          {children}
        </LayoutProvider>
</ClientWrapper>
      </body>
    </html>
  );
}






// import type { Metadata } from "next";
// import "./globals.css";
// import { LayoutProvider } from "@/context/LayoutContext";


// export const metadata: Metadata = {
//   title: "P-2-P | Admin Panel",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`antialiased`}
//       >
//         <LayoutProvider>
//           {children}
//         </LayoutProvider>
//       </body>
//     </html>
//   );
// }
